#' Order Trades
#'
#' Returns Listed Trades Generated By Open Order
#' @param oid, character: order identification number
#' @keywords order,trades
#' @export
#' @examples
#' order_trades("00K4kdad22Jaoij4Kahsfd")

order_trades<-function(oid){
  
  url<-"https://api.bitso.com/v3/order_trades/"
  NC<-NONCE()
  mthd<-"GET"
  Pyld<-""
  url<-paste0(url,oid,"/")
  Pth<-substr(url,22,nchar(url))
  hdr<-paste0("Bitso ",ky,":",NC,":",openssl::sha256(paste0(NC,mthd,Pth,Pyld),scrt))
  tmp <- tempfile()
  res<-httr::GET(url, httr::add_headers(Authorization=hdr), httr::write_disk(tmp))
  cat(noquote(paste("Success:", httr::content(res)$success,"\n\n")))
  if(httr::content(res)$success== TRUE){
    return(suppressWarnings(jsonlite::fromJSON(readLines(tmp)))$payload)
  }
}